name: Prepare CLI

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
    - shell: bash
      run: |
        bun install
        bun link
    - shell: bash
      name: Power cycle USB ports
      run: |
        uhubctl -l 2 -a 0 -N || true
        uhubctl -l 4 -a 0 -N || true
        sleep 1
        uhubctl -l 2 -a 1 -N || true
        uhubctl -l 4 -a 1 -N || true
        sleep 1
