name: Prepare CLI

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v1
    - shell: bash
      run: |
        bun install
        bun link
    - shell: bash
      name: Power cycle USB ports
      run: |
        END=4
        for i in $(seq 1 $END); do uhubctl -l $i -a off || true; done
        sleep 1
        for i in $(seq 1 $END); do uhubctl -l $i -a on || true; done
        sleep 1
