name: HITL

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun link

#      - run: sudo usbreset 05c6:9008
      - name: USB Reset
        run: |
          BUS_DEV=$(lsusb -d 05c6:9008 | awk '{print $2 "/" $4}' | sed 's/://')
          if [ -z "$BUS_DEV" ]; then
            echo "Device not found!"
            exit 1
          fi
          echo "Found device at /dev/bus/usb/$BUS_DEV"
          SYSFS_PATH=$(udevadm info -q path -n /dev/bus/usb/$BUS_DEV)
          if [ -z "$SYSFS_PATH" ]; then
            echo "Unable to determine sysfs path!"
            exit 1
          fi
          DEVICE_PATH=$(basename "$SYSFS_PATH")
          echo "$DEVICE_PATH" | sudo tee /sys/bus/usb/drivers/usb/unbind
          sleep 2
          echo "$DEVICE_PATH" | sudo tee /sys/bus/usb/drivers/usb/bind
          echo "Reset complete!"

      - run: qdl.js reset
      - run: qdl.js
