name: HITL

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    name: Test connection and CLI
    runs-on: [self-hosted, Linux, HITL]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/prepare-cli

      - name: connect to qdl (upload loader)
        run: qdl.js getactiveslot
      - name: connect to qdl (existing loader)
        run: qdl.js getactiveslot

      - name: qdl.js reset
        run: |
          qdl.js reset
          sleep 1
          qdl.js getactiveslot

      - run: qdl.js printgpt

      - run: qdl.js erase boot_a

      - name: download boot image
        run: |
          url=$(curl https://raw.githubusercontent.com/commaai/openpilot/master/system/hardware/tici/agnos.json | jq -r ".[] | select(.name == \"boot\") | .url")
          curl -L $url | unxz > boot.img

      - run: qdl.js flash boot_a ./boot.img
