name: HITL

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref == 'refs/heads/master' && github.run_id || github.head_ref || github.ref }}-${{ github.workflow }}-${{ github.event_name }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  test:
    runs-on: [self-hosted, Linux]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1

      - run: bun install
      - run: bun link

      - name: Power cycle USB ports
        run: |
          sudo uhubctl -s QUSB -a cycle || sudo uhubctl -l 1-1 -a on
          sleep 1

      - run: qdl.js
